name: Salebike
favicon: null
layout_spectrum: 0.74482
typography_spectrum: 0.5188131828326732
title: Bargains
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#000000'
    - '#bdbdbd'
    - '#ff5d5d'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.9774598537478596
  rhythmicContrast: 0.5
purpose: []
